version: '3.8'
services:
  backend:
    image: node:18-alpine
    container_name: app_backend
    working_dir: /app
    volumes:
      - ./Server:/app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: testdb
    command: sh -c "npm install && npm run start"
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    container_name: app_frontend
    working_dir: /app
    volumes:
      - ./Client:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"

  db:
    image: postgres:latest
    container_name: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: